### ISSUE TITLE
when i tried to run ansible-playbook i got this. Any idea?

### ISSUE THREAD

**Issue by bleckmeister** [lmakonem/ELK-SIEM-Ansible-Playbook#3]
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (specifiers.py, line 39)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 104, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 21, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 38, in <module>
    from ansible.plugins.loader import inventory_loader
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 35, in <module>
    from packaging.specifiers import SpecifierSet
  File "/usr/lib/python2.7/site-packages/packaging/specifiers.py", line 39
    class BaseSpecifier(metaclass=abc.ABCMeta):
                                 ^
SyntaxError: invalid syntax

**Comment by SpadaSchiavonesca** [comment]
Check Python Version Compatibility. Ensure that Ansible and its dependencies are running in a Python 3 environment. Ansible 2.8 and later versions require Python 3.5+ for most functionalities, although some backward compatibility with Python 2.7 exists. However, the packaging module likely expects Python 3.

You can check the Python version being used by Ansible by running: 
```bash
python --version
ansible --version
```
If shows Python 2.7, you'll need to install Python 3.
```bash
sudo apt-get update
sudo apt-get install python3
```
Assuming that you are running Debian/Ubuntu
